import type { SiteConfig } from '../types/config';

export const CONFIG: SiteConfig = {
    github: {
        username: 'hambosto',
        excludeRepos: [],
    },

    personal: {
        name: 'Ilham Putra Husada',
        title: 'Software Engineer',
        subtitle: 'Backend Engineering · Go · Rust · Distributed Systems',
        bio: 'Software Engineer specializing in backend systems and distributed architecture. I build high-performance, production-grade services using Go (Fiber, Gin, Echo, Chi, GORM, sqlx, pgx, zap, cobra) and Rust (Axum, Actix Web, Tokio, Serde, SQLx, Diesel, tracing, tower, clap). Experienced in designing RESTful APIs, gRPC services (tonic, Protobuf), and event-driven systems with RabbitMQ, AWS SQS, Kafka, NATS, and Redis Pub/Sub. Proficient in PostgreSQL, MySQL, Redis, MongoDB, and SQLite. Skilled in object storage with AWS S3, MinIO, and Google Cloud Storage. Experienced with Docker, Kubernetes, AWS (EC2, S3, Lambda, SQS, RDS), Nginx, Terraform, and CI/CD. Deep understanding of Microservices, CQRS, and Saga patterns. Committed to observability with Prometheus, Grafana, OpenTelemetry, Jaeger, and pprof. Focused on security with JWT, OAuth 2.0, OIDC, Rate Limiting, TLS/mTLS, and Vault. Passionate about writing efficient, concurrent code and building infrastructure that scales.',
        email: 'hambosto@gmail.com',
        resume: '/portofolio/resume.pdf',
        website: 'https://hambosto.github.io/portofolio',
    },

    social: {
        github: 'https://github.com/hambosto',
        linkedin: 'https://linkedin.com/in/hambosto',
        twitter: 'https://twitter.com/hambosto',
        email: 'hambosto@gmail.com',
    },

    quote: '"Simplicity is the soul of efficiency." — Austin Freeman',

    funFacts: [
        '🍜 Favorite fuel: Mie Ayam + Es Teh',
        '⌨️ Mechanical keyboard enthusiast',
        '🐧 Linux user — NixOS on the daily',
        '🦀 Rustacean in training',
        '📚 Currently reading: Designing Data-Intensive Applications',
        '☕ Tea over coffee, always',
    ],

    customSkills: {
        languages: [
            { name: 'Go', level: 90 },
            { name: 'Rust', level: 88 },
            { name: 'Python', level: 75 },
            { name: 'SQL', level: 82 },
            { name: 'TypeScript', level: 70 },
            { name: 'Bash / Shell', level: 85 },
        ],
        goWeb: [
            { name: 'Fiber', level: 88 },
            { name: 'Gin', level: 85 },
            { name: 'Echo', level: 82 },
            { name: 'Chi', level: 80 },
            { name: 'net/http (stdlib)', level: 88 },
            { name: 'fasthttp', level: 75 },
        ],
        goLibraries: [
            { name: 'GORM', level: 82 },
            { name: 'sqlx', level: 85 },
            { name: 'pgx', level: 80 },
            { name: 'go-redis/redis', level: 82 },
            { name: 'uber-go/zap', level: 80 },
            { name: 'sirupsen/logrus', level: 78 },
            { name: 'go-playground/validator', level: 82 },
            { name: 'golang-jwt/jwt', level: 80 },
            { name: 'gorilla/websocket', level: 75 },
            { name: 'spf13/cobra (CLI)', level: 85 },
        ],
        rustWeb: [
            { name: 'Axum', level: 85 },
            { name: 'Actix Web', level: 80 },
            { name: 'Rocket', level: 72 },
            { name: 'Warp', level: 70 },
            { name: 'Poem', level: 65 },
        ],
        rustLibraries: [
            { name: 'Tokio', level: 85 },
            { name: 'Serde', level: 88 },
            { name: 'SQLx', level: 82 },
            { name: 'Diesel', level: 78 },
            { name: 'tracing / tracing-subscriber', level: 80 },
            { name: 'tower / tower-http', level: 78 },
            { name: 'tokio-util', level: 75 },
            { name: 'hyper', level: 72 },
            { name: 'reqwest', level: 80 },
            { name: 'clap (CLI)', level: 82 },
        ],
        grpc: [
            { name: 'gRPC-Go', level: 80 },
            { name: 'gRPC-Rust (tonic)', level: 78 },
            { name: 'Protocol Buffers', level: 82 },
            { name: 'gRPC-Gateway', level: 72 },
            { name: 'Buf', level: 70 },
        ],
        messaging: [
            { name: 'RabbitMQ (amqp)', level: 82 },
            { name: 'AWS SQS / SNS', level: 78 },
            { name: 'Apache Kafka (sarama)', level: 75 },
            { name: 'NATS', level: 70 },
            { name: 'Redis Pub/Sub', level: 80 },
            { name: 'CloudEvents', level: 68 },
        ],
        databases: [
            { name: 'PostgreSQL', level: 85 },
            { name: 'MySQL / MariaDB', level: 78 },
            { name: 'Redis', level: 82 },
            { name: 'MongoDB', level: 72 },
            { name: 'SQLite', level: 75 },
            { name: 'ClickHouse', level: 65 },
        ],
        storage: [
            { name: 'AWS S3', level: 82 },
            { name: 'MinIO', level: 78 },
            { name: 'Google Cloud Storage', level: 70 },
            { name: 'Azure Blob Storage', level: 68 },
            { name: 'R2 (Cloudflare)', level: 65 },
            { name: 'SeaweedFS', level: 60 },
        ],
        infrastructure: [
            { name: 'Docker / Docker Compose', level: 85 },
            { name: 'Kubernetes', level: 75 },
            { name: 'AWS (EC2, S3, Lambda, SQS, RDS)', level: 80 },
            { name: 'Nginx / Traefik', level: 78 },
            { name: 'CI/CD (GitHub Actions)', level: 82 },
            { name: 'Terraform', level: 70 },
            { name: 'Makefile', level: 80 },
        ],
        architecture: [
            { name: 'REST API Design', level: 90 },
            { name: 'Microservices', level: 82 },
            { name: 'Event-Driven Architecture', level: 78 },
            { name: 'CQRS', level: 70 },
            { name: 'Saga Pattern', level: 68 },
            { name: 'System Design', level: 80 },
        ],
        observability: [
            { name: 'Prometheus / Grafana', level: 78 },
            { name: 'OpenTelemetry', level: 72 },
            { name: 'Jaeger / Zipkin', level: 70 },
            { name: 'Structured Logging', level: 85 },
            { name: 'Health Checks / Readiness', level: 88 },
            { name: 'pprof (Go profiling)', level: 75 },
        ],
        security: [
            { name: 'JWT / OAuth 2.0 / OIDC', level: 82 },
            { name: 'API Keys / Rate Limiting', level: 80 },
            { name: 'CORS / CSRF Protection', level: 78 },
            { name: 'Input Validation', level: 85 },
            { name: 'TLS / mTLS', level: 72 },
            { name: 'Hashicorp Vault', level: 65 },
        ],
    },

    education: [
        {
            id: '1',
            institution: 'Raden Rahmat Islamic University',
            degree: "Bachelor's Degree",
            field: 'Computer Science',
            location: 'Malang, Indonesia',
            startDate: '2022',
            description:
                'Studying computer science fundamentals including data structures, algorithms, operating systems, databases, computer networks, and software engineering. Active in open-source development with a focus on backend systems and infrastructure tools.',
            achievements: [
                'Built 13+ open-source backend and systems projects',
                'Developed concurrent systems in Go and Rust',
                'Self-taught distributed systems and message queues',
                'Daily NixOS user with deep Linux systems knowledge',
            ],
        },
    ],

    workExperience: [
        {
            id: '1',
            company: 'Open Source',
            position: 'Software Engineer',
            location: 'Malang, Indonesia',
            startDate: '2022-05',
            description:
                'Designing and building backend systems, APIs, and infrastructure utilities using Go and Rust. Experienced with Fiber, Gin, Echo, and Chi for Go services, and Axum, Actix Web for Rust services. Built event-driven architectures with RabbitMQ and AWS SQS, implemented gRPC microservices with tonic, and designed RESTful APIs with comprehensive authentication, rate limiting, and observability. Focus on performance, concurrency, security, and production-grade reliability.',
            technologies: [
                'Go',
                'Rust',
                'Fiber',
                'Gin',
                'Axum',
                'Actix Web',
                'RabbitMQ',
                'AWS SQS',
                'PostgreSQL',
                'Redis',
                'gRPC',
                'Docker',
                'Linux',
            ],
            achievements: [
                'Built go-downloader — concurrent file downloader with configurable workers, chunk-based parallel downloads, and progress tracking',
                'Developed sweetbyte — cross-platform encryption service with AES-256 in both Go (Fiber) and Rust (Axum)',
                'Created shell-patcher — ELF binary analysis tool for extracting SHC-compiled shell scripts',
                'Built go-monitor — real-time system monitoring TUI with CPU, memory, disk, and network metrics',
                'Developed ether-cli — Ethereum wallet management CLI with balance checking and fund transfers',
                'Created amd-epp — dynamic CPU power management daemon for AMD processors on Linux',
                'Built wallpaper-rs — minimal Wayland wallpaper daemon with automatic switching',
            ],
        },
    ],

    projects: [
        {
            id: '1',
            name: 'go-downloader',
            description: 'A concurrent file downloader written in Go. Fast, efficient, and easy to use with customizable workers and chunk sizes for maximum throughput.',
            github: 'https://github.com/hambosto/go-downloader',
            technologies: ['Go', 'HTTP', 'Concurrency', 'io/multiwriter'],
            highlights: [
                'Multi-worker concurrent downloading with configurable parallelism',
                'Chunk-based file splitting for maximum bandwidth utilization',
                'Real-time progress bar and download speed monitoring',
                'Graceful error handling and resume support',
            ],
            featured: true,
        },
        {
            id: '2',
            name: 'sweetbyte',
            description: 'A small, simple, yet secure encryption tool. Available in both Go and Rust implementations with focus on cryptographic best practices.',
            github: 'https://github.com/hambosto/sweetbyte',
            technologies: ['Rust', 'Go', 'Cryptography', 'AES-256'],
            highlights: [
                'Dual implementation in Rust (Axum) and Go (Fiber) for cross-platform compatibility',
                'Secure encryption with modern cryptographic algorithms',
                'Minimal dependencies and small binary size',
                'Simple CLI interface for easy integration into workflows',
            ],
            featured: true,
        },
        {
            id: '3',
            name: 'shell-patcher',
            description: 'A tool to decode and extract original source code from SHC-compiled shell scripts by patching and analyzing ELF binaries.',
            github: 'https://github.com/hambosto/shell-patcher',
            technologies: ['Go', 'ELF', 'Binary Analysis', 'Security'],
            highlights: [
                'Extracts original scripts from SHC-compiled ELF binaries',
                'Binary patching and memory analysis techniques',
                'Useful for security auditing and script recovery',
                'Demonstrates understanding of ELF binary structure',
            ],
        },
        {
            id: '4',
            name: 'go-monitor',
            description: 'Modern terminal-based system monitoring with real-time metrics and elegant TUI for CPU, memory, disk, and network statistics.',
            github: 'https://github.com/hambosto/go-monitor',
            technologies: ['Go', 'TUI', 'System APIs', 'Real-time Metrics'],
            highlights: [
                'Real-time monitoring of CPU, memory, disk, and network usage',
                'Beautiful terminal UI with color-coded metrics and graphs',
                'Lightweight with minimal CPU and memory overhead',
                'Cross-platform support for Linux and macOS',
            ],
        },
        {
            id: '5',
            name: 'ether-cli',
            description: 'A CLI tool for creating, restoring, and managing Ethereum wallets. Check balances, send funds, and interact with ERC-20 tokens.',
            github: 'https://github.com/hambosto/ether-cli',
            technologies: ['Python', 'Ethereum', 'Web3', 'Cryptography'],
            highlights: [
                'Wallet creation and restoration from mnemonic seed phrases',
                'Balance checking and ETH/ERC-20 token transfers',
                'Secure key management with local encryption',
                'Support for multiple Ethereum networks (mainnet, testnets)',
            ],
        },
        {
            id: '6',
            name: 'amd-epp',
            description: 'Dynamic EPP (Energy Performance Preference) management for AMD CPUs. Automatically optimizes power/performance balance based on AC/battery status.',
            github: 'https://github.com/hambosto/amd-epp',
            technologies: ['Rust', 'Linux', 'AMD P-State', 'System Daemon'],
            highlights: [
                'Automatic EPP adjustment based on power source (AC vs battery)',
                'Supports amd-pstate-epp driver for modern AMD processors',
                'Lightweight background daemon with minimal resource usage',
                'Configurable profiles for different usage scenarios',
            ],
        },
        {
            id: '7',
            name: 'wallpaper-rs',
            description: 'A minimal wallpaper daemon for Wayland compositors, written in Rust. Handles wallpaper switching and image scaling efficiently.',
            github: 'https://github.com/hambosto/wallpaper-rs',
            technologies: ['Rust', 'Wayland', 'Linux', 'Image Processing'],
            highlights: [
                'Native Wayland support — no X11 dependencies',
                'Minimal memory footprint and CPU usage',
                'Automatic wallpaper switching with configurable intervals',
                'Support for multiple monitors and different scaling modes',
            ],
        },
        {
            id: '8',
            name: 'portofolio',
            description: 'A terminal-style portfolio website built as a full desktop environment with draggable windows, multiple apps, and theme switching.',
            url: 'https://hambosto.github.io/portofolio',
            github: 'https://github.com/hambosto/portofolio',
            technologies: ['TypeScript', 'React', 'Vite', 'Tailwind CSS'],
            highlights: [
                'Full desktop environment simulation with custom window manager',
                'Interactive terminal emulator with 25+ commands',
                '20+ color themes including Catppuccin, Nord, Dracula',
                'Particle wallpaper with real-time mouse interaction',
            ],
        },
    ],
};
