import type { SiteConfig } from '../types/config';

export const CONFIG: SiteConfig = {
    github: {
        username: 'hambosto',
        excludeRepos: [],
    },

    personal: {
        name: 'Ilham Putra Husada',
        title: 'Software Engineer',
        subtitle: 'Backend Engineering · Go · Rust · SRE · Observability',
        bio: 'CS Student at Raden Rahmat Islamic University building production-grade backend systems. Specializing in high-performance services with Go (Fiber, Gin, Echo, Chi, GORM, ent, sqlx, pgx, zap) and Rust (Axum, Actix Web, Tokio, Serde, SQLx, tracing, tower). Building event-driven architectures with RabbitMQ, AWS SQS, Kafka, NATS, and Redis. Deep understanding of Microservices, CQRS, and Clean Architecture. Strong in observability with Sentry, OpenTelemetry, Prometheus, Grafana, and structured logging. Passionate about writing efficient, concurrent code and building infrastructure that scales.',
        email: 'hambosto@gmail.com',
        resume: '/portofolio/resume.pdf',
        website: 'https://hambosto.github.io/portofolio',
    },

    social: {
        github: 'https://github.com/hambosto',
        linkedin: 'https://linkedin.com/in/hambosto',
        twitter: 'https://twitter.com/hambosto',
        email: 'hambosto@gmail.com',
    },

    quote: '"Simplicity is the soul of efficiency." — Austin Freeman',

    funFacts: [
        '🍜 Favorite fuel: Mie Ayam + Es Teh',
        '⌨️ Mechanical keyboard enthusiast',
        '🐧 Daily NixOS user — declarative config for life',
        '🦀 Rustacean in training',
        '📚 Reading: Designing Data-Intensive Applications',
        '☕ Tea over coffee, always',
        '🎯 13+ open-source projects on GitHub',
    ],

    customSkills: {
        languages: [
            { name: 'Go', level: 90 },
            { name: 'Rust', level: 88 },
            { name: 'Python', level: 75 },
            { name: 'SQL', level: 82 },
            { name: 'TypeScript', level: 70 },
            { name: 'Nix', level: 75 },
            { name: 'Bash / Shell', level: 85 },
        ],
        goWeb: [
            { name: 'Fiber', level: 90 },
            { name: 'Gin', level: 88 },
            { name: 'Echo', level: 85 },
            { name: 'Chi', level: 82 },
            { name: 'net/http (stdlib)', level: 90 },
            { name: 'fasthttp', level: 75 },
            { name: 'Hertz', level: 70 },
        ],
        goLibraries: [
            { name: 'GORM', level: 85 },
            { name: 'ent', level: 82 },
            { name: 'sqlx', level: 88 },
            { name: 'pgx', level: 85 },
            { name: 'go-redis/redis', level: 88 },
            { name: 'uber-go/zap', level: 85 },
            { name: 'sirupsen/logrus', level: 80 },
            { name: 'go-playground/validator', level: 85 },
            { name: 'golang-jwt/jwt', level: 85 },
            { name: 'gorilla/websocket', level: 80 },
            { name: 'spf13/cobra (CLI)', level: 88 },
            { name: 'stretchr//testify', level: 82 },
            { name: 'testify/mock', level: 80 },
        ],
        rustWeb: [
            { name: 'Axum', level: 88 },
            { name: 'Actix Web', level: 85 },
            { name: 'Rocket', level: 75 },
            { name: 'Warp', level: 72 },
            { name: 'Poem', level: 68 },
            { name: 'Salvo', level: 65 },
        ],
        rustLibraries: [
            { name: 'Tokio', level: 88 },
            { name: 'Serde', level: 92 },
            { name: 'SQLx', level: 85 },
            { name: 'Diesel', level: 78 },
            { name: 'tracing / tracing-subscriber', level: 85 },
            { name: 'tower / tower-http', level: 82 },
            { name: 'tokio-util', level: 80 },
            { name: 'hyper', level: 78 },
            { name: 'reqwest', level: 85 },
            { name: 'clap (CLI)', level: 88 },
            { name: 'thiserror', level: 85 },
            { name: 'anyhow', level: 82 },
            { name: 'once_cell', level: 80 },
        ],
        grpc: [
            { name: 'gRPC-Go', level: 82 },
            { name: 'gRPC-Rust (tonic)', level: 80 },
            { name: 'Protocol Buffers', level: 85 },
            { name: 'gRPC-Gateway', level: 75 },
            { name: 'Buf', level: 72 },
            { name: 'grpcurl', level: 78 },
        ],
        messaging: [
            { name: 'RabbitMQ (amqp)', level: 85 },
            { name: 'AWS SQS / SNS', level: 82 },
            { name: 'Apache Kafka (sarama)', level: 78 },
            { name: 'NATS', level: 75 },
            { name: 'Redis Pub/Sub', level: 85 },
            { name: 'CloudEvents', level: 72 },
            { name: 'MessagePack', level: 75 },
        ],
        databases: [
            { name: 'PostgreSQL', level: 90 },
            { name: 'MySQL / MariaDB', level: 82 },
            { name: 'Redis', level: 88 },
            { name: 'MongoDB', level: 75 },
            { name: 'SQLite', level: 78 },
            { name: 'ClickHouse', level: 68 },
            { name: 'DynamoDB', level: 70 },
        ],
        storage: [
            { name: 'AWS S3', level: 85 },
            { name: 'MinIO', level: 80 },
            { name: 'Google Cloud Storage', level: 72 },
            { name: 'Azure Blob Storage', level: 70 },
            { name: 'Cloudflare R2', level: 68 },
            { name: 'SeaweedFS', level: 62 },
        ],
        infrastructure: [
            { name: 'Docker / Docker Compose', level: 90 },
            { name: 'Kubernetes', level: 78 },
            { name: 'AWS (EC2, S3, Lambda, SQS, RDS)', level: 82 },
            { name: 'Nginx / Traefik', level: 82 },
            { name: 'GitHub Actions', level: 88 },
            { name: 'Terraform', level: 75 },
            { name: 'Ansible', level: 72 },
            { name: 'Makefile', level: 85 },
            { name: 'Nix / NixOS', level: 78 },
        ],
        architecture: [
            { name: 'REST API Design', level: 92 },
            { name: 'Microservices', level: 85 },
            { name: 'Event-Driven Architecture', level: 82 },
            { name: 'CQRS', level: 75 },
            { name: 'Saga Pattern', level: 72 },
            { name: 'System Design', level: 85 },
            { name: 'DDD', level: 75 },
            { name: 'Clean Architecture', level: 80 },
        ],
        observability: [
            { name: 'Sentry', level: 85 },
            { name: 'OpenTelemetry (OTel)', level: 82 },
            { name: 'Prometheus / Grafana', level: 85 },
            { name: 'Jaeger / Zipkin', level: 78 },
            { name: 'Structured Logging', level: 90 },
            { name: 'Health Checks / Readiness', level: 92 },
            { name: 'pprof (Go profiling)', level: 82 },
            { name: ' flamegraph', level: 75 },
            { name: 'Metrics (Prometheus client)', level: 80 },
        ],
        security: [
            { name: 'JWT / OAuth 2.0 / OIDC', level: 85 },
            { name: 'API Keys / Rate Limiting', level: 85 },
            { name: 'CORS / CSRF Protection', level: 82 },
            { name: 'Input Validation', level: 90 },
            { name: 'TLS / mTLS', level: 78 },
            { name: 'Hashicorp Vault', level: 70 },
            { name: 'WireGuard', level: 72 },
            { name: 'CrowdSec', level: 68 },
        ],
    },

    education: [
        {
            id: '1',
            institution: 'Raden Rahmat Islamic University',
            degree: "Bachelor's Degree",
            field: 'Computer Science',
            location: 'Malang, Indonesia',
            startDate: '2022',
            description:
                'Studying computer science fundamentals including data structures, algorithms, operating systems, databases, computer networks, and software engineering. Focused on backend systems, distributed systems, and site reliability engineering.',
            achievements: [
                'Built 13+ open-source backend and systems projects',
                'Developed concurrent systems in Go and Rust',
                'Self-taught distributed systems, message queues, and observability',
                'Daily NixOS user with deep Linux systems knowledge',
            ],
        },
    ],

    workExperience: [
        {
            id: '1',
            company: 'Open Source',
            position: 'Software Engineer',
            location: 'Malang, Indonesia',
            startDate: '2022-05',
            description:
                'Building backend systems, APIs, and infrastructure tools using Go and Rust. Focused on CLI tools, system utilities, cryptography, and Linux system programming. Built CLI encryption tools, system monitors, and daemons with focus on performance, concurrency, and production-grade reliability.',
            technologies: [
                'Go',
                'Rust',
                'CLI',
                'Cryptography',
                'TUI',
                'PostgreSQL',
                'Redis',
                'Docker',
                'Linux',
                'NixOS',
            ],
            achievements: [
                'Built wallpaper-rs — minimal Wayland wallpaper daemon with automatic switching and multi-monitor support',
                'Developed sweetbyte (Go + Rust) — secure AES-256-GCM encryption CLI tool',
                'Created shell-patcher — ELF binary analysis tool for extracting SHC-compiled shell scripts',
                'Built go-monitor — real-time system monitoring TUI with CPU, memory, disk, and network metrics',
                'Developed ether-cli — Ethereum wallet management CLI with balance checking and fund transfers',
                'Created amd-epp — dynamic CPU power management daemon for AMD processors on Linux',
                'Built nixos — declarative NixOS configuration with home manager and modular dotfiles',
            ],
        },
    ],

    projects: [
        {
            id: '1',
            name: 'wallpaper-rs',
            description:
                'A minimal wallpaper daemon for Wayland compositors, written in Rust. Handles wallpaper switching and image scaling efficiently.',
            github: 'https://github.com/hambosto/wallpaper-rs',
            technologies: ['Rust', 'Wayland', 'Linux', 'Image Processing'],
            highlights: [
                'Native Wayland support — no X11 dependencies',
                'Minimal memory footprint and CPU usage',
                'Automatic wallpaper switching with configurable intervals',
                'Support for multiple monitors and different scaling modes',
            ],
            featured: true,
        },
        {
            id: '2',
            name: 'go-downloader',
            description:
                'A concurrent file downloader written in Go. Fast, efficient, and easy to use with customizable workers and chunk sizes for maximum throughput.',
            github: 'https://github.com/hambosto/go-downloader',
            technologies: ['Go', 'HTTP', 'Concurrency', 'io/multiwriter'],
            highlights: [
                'Multi-worker concurrent downloading with configurable parallelism',
                'Chunk-based file splitting for maximum bandwidth utilization',
                'Real-time progress bar and download speed monitoring',
                'Graceful error handling and resume support',
            ],
            featured: true,
        },
        {
            id: '2',
            name: 'sweetbyte',
            description:
                'A very small, simple, yet secure CLI encryption tool written in Go with AES-256-GCM.',
            github: 'https://github.com/hambosto/sweetbyte',
            technologies: ['Go', 'Cryptography', 'AES-256-GCM', 'CLI'],
            highlights: [
                'Secure encryption with AES-256-GCM authenticated encryption',
                'Interactive and CLI modes for different use cases',
                'Minimal dependencies and small binary size',
                'Cross-platform support (Linux, macOS, Windows)',
            ],
            featured: true,
        },
        {
            id: '3',
            name: 'sweetbyte-rs',
            description:
                'Rust implementation of sweetbyte — a secure encryption CLI tool using AES-256-GCM.',
            github: 'https://github.com/hambosto/sweetbyte-rs',
            technologies: ['Rust', 'Cryptography', 'AES-256-GCM', 'CLI'],
            highlights: [
                'Pure Rust implementation using ring/bedrock crypto',
                'Streaming encryption for large files',
                'Small binary size (~1MB) and fast execution',
                'Nix flake for reproducible builds',
            ],
            featured: true,
        },
        {
            id: '4',
            name: 'shell-patcher',
            description:
                'A tool to decode and extract original source code from SHC-compiled shell scripts by patching and analyzing ELF binaries.',
            github: 'https://github.com/hambosto/shell-patcher',
            technologies: ['Go', 'ELF', 'Binary Analysis', 'Security'],
            highlights: [
                'Extracts original scripts from SHC-compiled ELF binaries',
                'Binary patching and memory analysis techniques',
                'Useful for security auditing and script recovery',
                'Demonstrates understanding of ELF binary structure',
            ],
        },
        {
            id: '5',
            name: 'go-monitor',
            description:
                'Modern terminal-based system monitoring with real-time metrics and elegant TUI for CPU, memory, disk, and network statistics.',
            github: 'https://github.com/hambosto/go-monitor',
            technologies: ['Go', 'TUI', 'System APIs', 'Real-time Metrics'],
            highlights: [
                'Real-time monitoring of CPU, memory, disk, and network usage',
                'Beautiful terminal UI with color-coded metrics and graphs',
                'Lightweight with minimal CPU and memory overhead',
                'Cross-platform support for Linux and macOS',
            ],
        },
        {
            id: '6',
            name: 'ether-cli',
            description:
                'A CLI tool for creating, restoring, and managing Ethereum wallets. Check balances, send funds, and interact with ERC-20 tokens.',
            github: 'https://github.com/hambosto/ether-cli',
            technologies: ['Python', 'Ethereum', 'Web3', 'Cryptography'],
            highlights: [
                'Wallet creation and restoration from mnemonic seed phrases',
                'Balance checking and ETH/ERC-20 token transfers',
                'Secure key management with local encryption',
                'Support for multiple Ethereum networks (mainnet, testnets)',
            ],
        },
        {
            id: '7',
            name: 'amd-epp',
            description:
                'Dynamic EPP (Energy Performance Preference) management for AMD CPUs. Automatically optimizes power/performance balance based on AC/battery status.',
            github: 'https://github.com/hambosto/amd-epp',
            technologies: ['Rust', 'Linux', 'AMD P-State', 'System Daemon'],
            highlights: [
                'Automatic EPP adjustment based on power source (AC vs battery)',
                'Supports amd-pstate-epp driver for modern AMD processors',
                'Lightweight background daemon with minimal resource usage',
                'Configurable profiles for different usage scenarios',
            ],
        },
        {
            id: '8',
            name: 'portofolio',
            description:
                'A terminal-style portfolio website built as a full desktop environment with draggable windows, multiple apps, and theme switching.',
            url: 'https://hambosto.github.io/portofolio',
            github: 'https://github.com/hambosto/portofolio',
            technologies: ['TypeScript', 'React', 'Vite', 'Tailwind CSS'],
            highlights: [
                'Full desktop environment simulation with custom window manager',
                'Interactive terminal emulator with 25+ commands',
                '20+ color themes including Catppuccin, Nord, Dracula',
                'Particle wallpaper with real-time mouse interaction',
            ],
        },
        {
            id: '9',
            name: 'nixos',
            description:
                'My NixOS configuration with declarative system management, home manager, and personalized dotfiles.',
            github: 'https://github.com/hambosto/nixos',
            technologies: ['Nix', 'NixOS', 'Home Manager', 'Linux'],
            highlights: [
                'Declarative system configuration using Nix flakes',
                'Modular dotfiles managed via Home Manager',
                'Reproducible development environments',
                'Automated system setup from scratch',
            ],
        },
        {
            id: '10',
            name: 'sweetbyte-rs',
            description:
                'Rust implementation of sweetbyte — a secure encryption tool using AES-256 with modern cryptographic practices.',
            github: 'https://github.com/hambosto/sweetbyte-rs',
            technologies: ['Rust', 'Cryptography', 'AES-256', 'CLI'],
            highlights: [
                'Pure Rust implementation with no external crypto dependencies',
                'AES-256-GCM encryption with authenticated data',
                'Small binary size and fast execution',
                'Simple CLI for encrypting files and messages',
            ],
        },
        {
            id: '11',
            name: 'ethereum-vanity',
            description:
                'A high-performance, multi-threaded Ethereum vanity wallet generator written in Rust.',
            github: 'https://github.com/hambosto/ethereum-vanity',
            technologies: ['Rust', 'Ethereum', 'Cryptography', 'Concurrency'],
            highlights: [
                'Multi-threaded address generation for maximum throughput',
                'Custom prefix/suffix matching for vanity addresses',
                'Efficient key derivation from deterministic wallets',
                'Benchmark-optimized for modern CPUs',
            ],
        },
    ],
};
